spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/marketing_trade
    username: postgres
    password: Rpraveen@123

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

server:
  port: 8085

app:
  seed:
    enabled: true